jobs:
  allow_failures:
    - os: windows
  include:

    - os: linux
      dist: bionic
      language: rust
      before_install:
          - sudo apt-get update -q
          - sudo apt-get install libsqlcipher-dev -y
          - nvm install $TRAVIS_NODE_VERSION
          - nvm use ${TRAVIS_NODE_VERSION}
      env:
        - TRAVIS_NODE_VERSION="12"

    - os: osx
      language: rust
      before_install:
          - HOMEBREW_NO_AUTO_UPDATE=1 brew install sqlcipher
          - nvm install $TRAVIS_NODE_VERSION
          - nvm use ${TRAVIS_NODE_VERSION}
      env:
        - TRAVIS_NODE_VERSION="12"

    - os: windows
      language: rust
      before_install:
          - git clone --single-branch https://github.com/jasongin/nvs $NVS_HOME
          - source $NVS_HOME/nvs.sh
          - nvs --version
          - nvs add $TRAVIS_NODE_VERSION && nvs use $TRAVIS_NODE_VERSION
          - choco install sqlite
      env:
        - TRAVIS_NODE_VERSION="12"
        - NVS_HOME=$ProgramData/nvs
      script:
          # There is no easy way to install SQLCipher under Windows so let's at
          # least run tests not requiring it.
          - cargo test --no-default-features

install:
  - node -v
  - npm -v
  - npm i -g yarn@latest neon-cli@latest

script:
  - cargo test
    # Reset our test data before running the Javascript tests
  - rm -r data/database
  - git reset --hard HEAD
  - cd seshat-node
  - yarn install
  - yarn test --coverage
  - yarn lint
