matrix:
  include:
    - os: linux
      language: rust
      env:
        - TRAVIS_NODE_VERSION="12"
    - os: osx
      language: rust
      env:
        - TRAVIS_NODE_VERSION="12"
    - os: windows
      language: rust
      env:
        - TRAVIS_NODE_VERSION="12"

cache: cargo

before_install:
  - nvm install $TRAVIS_NODE_VERSION
  - nvm use ${TRAVIS_NODE_VERSION}
  - node -v
  - npm -v
  - npm i -g yarn@latest neon-cli@latest
  - npm install

script:
  - cargo test
  - cd seshat-node
  - yarn install
  - yarn test
  - yarn lint
