[package]
name = "seshat"
version = "0.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
tantivy = "*"
rusqlite = "*"
r2d2_sqlite = "*"
r2d2 = "*"

[dev-dependencies]
tempfile = "*"
lazy_static = "*"
