[package]
name = "seshat"
version = "1.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "Apache-2.0"
description = "A matrix message logger with full text search support"
readme="README.md"

[features]
default = ["encryption"]
encryption = ["rusqlite/sqlcipher"]

[dependencies]
tantivy = "0.12.0"
tinysegmenter = "0.1.1"
rusqlite = "0.21.0"
fs_extra = "1.1.0"
r2d2_sqlite = "0.13.0"
r2d2 = "0.8.8"
failure = "0.1.6"
aes-ctr = "0.3.0"
crypto-mac = "0.7.0"
hmac = "0.7.1"
sha2 = "0.8.1"
hkdf = "0.8.0"
pbkdf2 = "0.3.0"
rand = "0.7.3"
zeroize = "1.1.0"
byteorder = "1.3.2"
serde_json = "1.0.48"

[dev-dependencies]
tempfile = "3.1.0"
lazy_static = "1.4.0"
fake = "2.2.0"
