[package]
name = "seshat"
version = "0.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "Apache-2.0"
description = "A matrix message logger with full text search support"

[dependencies]
tantivy = { git = "https://github.com/tantivy-search/tantivy" }
rusqlite = "0.20"
r2d2_sqlite = "0.12"
r2d2 = "0.8"

[dev-dependencies]
tempfile = "3.1"
lazy_static = "1.3"
