[package]
name = "matrix-search"
version = "0.1.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
edition = "2018"
license = "Apache 2"

[lib]
crate-type = ["cdylib"]

[dependencies]

tantivy = "*"
tempfile = "*"
rusqlite = "*"
r2d2_sqlite = "*"
r2d2 = "*"
lazy_static = "*"
