[package]
name = "seshat-node"
version = "0.3.0"
authors = ["Damir Jelić <poljar@termina.org.uk>"]
license = "Apache-2.0"
build = "build.rs"
exclude = ["artifacts.json", "index.node"]
edition = "2018"

[lib]
name = "seshat_node"
crate-type = ["cdylib"]

[build-dependencies]
neon-build = "=0.3.3"

[dependencies]
neon = "=0.3.3"
fs_extra = "1.1.0"
serde_json = "1.0.44"
r2d2 = "0.8.8"
r2d2_sqlite = "0.13.0"
neon-serde = "=0.3.0"
seshat = { path = "../../" }
